version: "3.9"

services:
  saxon-xslt-service:
    image: eaglessoftbv/saxon-xslt-service:latest
    container_name: saxon-xslt-service
    ports:
      - "80:80"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/"
    restart: unless-stopped
